version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: orders_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: orders_db
      MYSQL_USER: orders_user
      MYSQL_PASSWORD: orders_pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    image: python:3.11-slim
    container_name: orders_backend
    restart: always
    working_dir: /app
    volumes:
      - ./backend:/app
    command: >
      sh -c "pip install flask mysql-connector-python &&
             python app.py"
    environment:
      DB_HOST: db
      DB_USER: orders_user
      DB_PASSWORD: orders_pass
      DB_NAME: orders_db
    depends_on:
      - db
    ports:
      - "5000:5000"

  frontend:
    image: nginx:latest
    container_name: orders_frontend
    restart: always
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  db_data:
